name: survicate_flutter_sdk
description: Survicate mobile survey SDK for Flutter.
version: 0.1.0
homepage: https://github.com/andre-paraense/lsurvicate-flutter-sdk
issue_tracker: https://github.com/andre-paraense/survicate-flutter-sdk/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.oakam.survicate.survicate_flutter_sdk
        pluginClass: SurvicateFlutterSdkPlugin
      ios:
        pluginClass: SurvicateFlutterSdkPlugin