name: CI

on: [push]

jobs: 
  build-and-test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1.3.2
        with:
          channel: 'stable'
      - run: flutter packages get
      - run: flutter analyze --no-pub
      - run: flutter test --coverage
      - run: flutter pub publish --dry-run